version: '3.8'
services:
  app:
    build: ./backend
    container_name: auven-backend
    ports: ["9000:9000"]
    volumes:
      - ./backend:/var/www/html
  web:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend/public:/var/www/html/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: auven
      MYSQL_USER: auven
      MYSQL_PASSWORD: auvenpass
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
