services:
  - type: web
    name: auven-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true

databases:
  - name: auven-db
    plan: free
    region: oregon
